server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
  datasource:
    ##?????????mysql
    url: jdbc:mysql://localhost:3306/xw?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-auto-commit: true
      init-sql: select 1 from dual
      max-active: 128
      max-idle: 10
      max-wait: 5000
      #???????????????完???:????
      min-evictable-idle-time-millis: 1800000
      #?????????????????????test-while-idle??????:????
      time-between-eviction-runs-millis: 900000
      #SQL ????????????????妊?????? 0 ????????????
      validation-query-timeout: 2
      #????????????完?????????????
      validation-interval: 120000
      #???????????????????????完?????,????????validationInterval, validationQuery
      test-on-borrow: true
      #???????????????孝???sql??????.
      validation-query: select 1 from dual
      #????我???????????????????????????????????????米??????????????validationInterval???????技??
      test-while-idle: true
  jpa:
    hibernate:
      ##validate  ????hibernate?????????????????
      ##create   ??米???hibernate???????????????????????????????????????????
      ##create-drop        ????hibernate??????????????????
      ##update                 ????hibernate?????????????
      ##validate ??????????????????????
      ##none  ??????????百汕???
      ddl-auto: update
    show-sql: true
    open-in-view: true

